### ISSUE TITLE
Plugin Discontinued?

### ISSUE THREAD

**Issue by TheEpicCooldeal** [Falkirks/BuyCraft#10]
Is the plugin discontinued? o.o the last plugin was in March.

Plus: The colors don't work When I put the "broadcast &e{name} &bhas purchased a package from our donation store!" It appears as: "broadcast &e{name} &bhas purchased a package from our donation store!"

I'm using the latest version of BuyCraft and the latest PocketMine Development build.

**Comment by Falkirks** [comment]
It hasn't been updated since colours were implemented, so they don't have any special support. It is definitely still supported, I have just been busy recently.
