### ISSUE TITLE
It doesn't work I put the key in and get an error

### ISSUE THREAD

**Issue by SpartanForLife** [Falkirks/BuyCraft#12]
I'm in 0.11.1 mcpe I have a Samsung galaxy s4 and I get an authentication error when I put the security key in

**Comment by Falkirks** [comment]
Are you running the server on Android, if so see #11

**Comment by SpartanForLife** [comment]
Yes I am using Android but I didn't understand how that helped I put key in like it says and I get an error

**Comment by Falkirks** [comment]
Further discussion should go to #11
