### ISSUE TITLE
Auth error on CentOS VPS?

### ISSUE THREAD

**Issue by legoboy0215** [Falkirks/BuyCraft#13]
Can anyone confirm this?

I use a DigitalOcean CentOS 6.5 x32 VPS. I tried EVERY version of BuyCraft, and it always gave me the same auth error. I have enabled Private Networking and even User data.
BuyCraft still did not work. Is there any way to solve this?

**Comment by jazzwhistle** [comment]
Hi, It's working fine for me - are you sure it's nothing to do with firewall rules?

**Comment by legoboy0215** [comment]
Fixed it long ago lol :)

**Comment by Falkirks** [comment]
@legoboy0215 Thanks for closing this :smile:
