### ISSUE TITLE
doesnt work with the new api

### ISSUE THREAD

**Issue by TDMGamingMC** [Falkirks/BuyCraft#14]
Hello so basically this plugin doesnt work now with imagicalmine! can you help fix it?

**Comment by SirAquarus** [comment]
This plugin is for PocketMine. **Not** ImagicalMine.

**Comment by SirAquarus** [comment]
Any changes they make to the API is up to them.

**Comment by blah123454321** [comment]
What's ImigicalMine

**Comment by blah123454321** [comment]
ImagicalMine*
