### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Tolo0** [Falkirks/BuyCraft#19]
sins the 14.2 update buycraft has stopped working for me. It ses this on the console. 

Server thread/INFO]: BuyCraft is not linked to buycraft.net and can't process purchases for you.
[13:12:25] [Server thread/INFO]: If you are the owner of this server you need to enter your secret key in the config.yml or using /buycraft secret <key>.

iv tried reseting the key but nothing works.

**Comment by Tolo0** [comment]
any help would be appreciated.

**Comment by Falkirks** [comment]
This plugin needs to be updated to use the new API, see #18.
