### ISSUE TITLE
Keeps getting error

### ISSUE THREAD

**Issue by FaZeFantasy** [Falkirks/BuyCraft#5]
when i do buycraft secret then the code it just keeps on giving me an error on game and console and it does have the secret code in the config

**Comment by Falkirks** [comment]
This error is being looked into.

**Comment by Drumpit** [comment]
Hi Falkirks!Please answer my Questions: 1.:Can I write you in a E-mail my Buycraft E-mail and Password? After you look if it works on your Server I can change my secret key and I can change my datas! Can you do this??? 
2.: Can you make a Tutorial how I configure Buycraft with VIP Slots???
3.: When a player buy anything,he pay money! But where I can confige at which Bank Account the money should be go???? 
4.: Please write back when you read this! And sorry for my badly English! I speak German!thanks

**Comment by FaZeFantasy** [comment]
It might work now cuz I 4got to pay for it so it might work now if I set it
up again we will just see and if it doesn't I will tell you what you want
to know.

**Comment by Drumpit** [comment]
Thanks but can you answer all Questions Falkirks????

**Comment by FaZeFantasy** [comment]
1. Don't know what you mean
2. yes
3. I haven't got to it cuz of the error

**Comment by Falkirks** [comment]
@Drumpit 
* No. I can test on my own account.
* Probably not. I don't have much time on my hands.
* That is something that buycraft.net handles, you can configure a bunch of payment gateways.

**Comment by Drumpit** [comment]
And this Bug.... have you fond it???

**Comment by FaZeFantasy** [comment]
????

**Comment by Drumpit** [comment]
Yes thanks! 
How I connect Buycraft with VIPSlots and a BankAccount???@Falkirks

**Comment by Falkirks** [comment]
Do either of those plugins have commands for management?

**Comment by Georggi** [comment]
@Drumpit VIPSlots has "/vips <add\remove>", watch https://youtu.be/vydmBue9rmk for tutorial of how to add a command.
